config/routes.rb
PizzaShop::Application.routes.draw do
  get  "home/index"

  resources :orders do
    get :execute
    get :cancel
  end

  devise_for :users

  root :to => "home#index"
end

app/models/credit_card.rb
class CreditCard < PayPal::SDK::REST::CreditCard
  extend ActiveModel::Naming
  include ActiveModel::Conversion
  include ActiveModel::Validations

  validates_presence_of :type, :number, :expire_month, :expire_year

  def create
    return true  if created?
    return false if invalid?
    unless super
      if error and error["details"]
        error["details"].each do |detail|
          errors.add detail["field"], detail["issue"]
        end
      else
        errors.add :type, error.inspect
      end
    end
    success?
  end

  def present?
    to_hash.present?
  end

  def created?
    self.id.present?
  end

  def description
    "xxxxxxxxxxxx#{number[-4..-1]} Expire on #{expire_month}/#{expire_year}"
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  attr_accessible :amount, :description, :state, :payment_method, :credit_card

  validates_presence_of :amount, :description, :user_id

  after_create :create_payment

  attr_accessor :return_url, :cancel_url, :payment_method

  validate do
    if payment_method == "credit_card" and ( user.credit_card_id.nil? || @credit_card.present? ) and @credit_card.invalid?
      errors.add :create_card, "Validation error"
    end
  end


  def payment
    @payment ||= payment_id && Payment.find(payment_id)
  end

  def credit_card
    user.credit_card
  end

  def credit_card=(hash)
    user.credit_card = hash
  end

  def create_payment
    if payment_method == "credit_card" and !user.save
      raise ActiveRecord::Rollback, "Can't place the order"
    end
    @payment = Payment.new( :order => self )
    if @payment.create
      self.payment_id = @payment.id
      self.state      = @payment.state
      save
    else
      errors.add :payment_method, @payment.error["message"] if @payment.error
      raise ActiveRecord::Rollback, "Can't place the order"
    end
  end

  def execute(payer_id)
    if payment.present? and payment.execute(:payer_id => payer_id)
      self.state = payment.state
      save
    else
      errors.add :description, payment.error.inspect
      false
    end
  end

  def approve_url
    payment.links.find{|link| link.method == "REDIRECT" }.try(:href)
  end

end

app/models/payment.rb
class Payment < PayPal::SDK::REST::Payment
  include ActiveModel::Validations

  def create
    return false if invalid?
    super
  end

  def error=(error)
    error["details"].each do |detail|
      errors.add detail["field"], detail["issue"]
    end if error and error["details"]
    super
  end


  def add_payment_method(order)
    user = order.user
    if order.payment_method == "credit_card" and user.credit_card_id
      self.payer.payment_method = "credit_card"
      self.payer.funding_instruments = {
        :credit_card_token => {
          :credit_card_id => user.credit_card_id,
          :payer_id => user.email }}
    else
      self.payer.payment_method = "paypal"
    end
  end

  def order=(order)
    self.intent = "sale"
    add_payment_method(order)
    self.transactions = {
      :amount => {
        :total => order.amount,
        :currency => "USD" },
      :item_list => {
        :items => { :name => "pizza", :sku => "pizza", :price => order.amount, :currency => "USD", :quantity => 1 }
      },
      :description => order.description
     }
     self.redirect_urls = {
       :return_url => order.return_url.sub(/:order_id/, order.id.to_s),
       :cancel_url => order.cancel_url.sub(/:order_id/, order.id.to_s)
     }
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :credit_card
  # attr_accessible :title, :body
  #

  has_many :orders

  attr_accessor :credit_card

  validate do
    if need_credit_card? and credit_card.invalid?
      errors.add :credit_card_id, "Validation error"
    end
  end

  before_save :create_credit_card, :if => :need_credit_card?

  def need_credit_card?
    # credit_card_id.nil? or credit_card.present?
    credit_card.present?
  end

  def create_credit_card
    credit_card.external_customer_id = self.email
    if credit_card.create
      self.credit_card_id          = credit_card.id
      self.credit_card_description = credit_card.description
      true
    else
      errors.add :credit_card_id, "Validation error"
      false
    end
  end

  def fetch_credit_card
    @fetch_credit_card ||= credit_card_id && CreditCard.find(credit_card_id)
  end

  def credit_card
    @credit_card ||= CreditCard.new
  end

  def credit_card=(hash)
    @credit_card = CreditCard.new(hash)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :authenticate_user!
  def index
    @orders = current_user.orders.all( :limit => 10, :order => "id DESC" )
  end

  def create
    @order = current_user.orders.build
    @order.attributes = params[:order]
    @order.return_url = order_execute_url(":order_id")
    @order.cancel_url = order_cancel_url(":order_id")
    if @order.payment_method and @order.save
      if @order.approve_url
        redirect_to @order.approve_url
      else
        redirect_to orders_path, :notice => "Order[#{@order.description}] placed successfully"
      end
    else
      render :create, :alert  => @order.errors.to_a.join(", ")
    end
  end

  def execute
    order = current_user.orders.find(params[:order_id])
    if order.execute(params["PayerID"])
      redirect_to orders_path, :notice => "Order[#{order.description}] placed successfully"
    else
      redirect_to orders_path, :alert => order.payment.error.inspect
    end
  end

  def cancel
    order = current_user.orders.find(params[:order_id])
    unless order.state == "approved"
      order.state = "cancelled"
      order.save
    end
    redirect_to orders_path, :alert => "Order[#{order.description}] cancelled"
  end

  def show
    @order = current_user.orders.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_li(name, path, *args)
    content_tag "li", :class => ( request.path == path ? "active" : "" ) do
      link_to name, path, *args
    end
  end

  def current_year
    @current_year ||= Time.now.year
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/home/index.html.haml
- 3.times do |row_index|
  .row.pizza-row
    - 6.times do |col_index|
      - index = row_index *6 + col_index
      .span2
        .image
          = image_tag "http://www.gravatar.com/avatar/000000000000000000000000000000#{index}?d=identicon&f=y",
            :alt => "Pizza #{index}"
        .details
          = "20$ - "
          = link_to "Buy", orders_path( :order => { :amount => 20, :description => "Pizza #{index}" }),
            :method => :post, :class => "btn btn-small", :disable_with => "Procesing.."

%br/
%br/
%br/
.row
  .span6.offset3
    %p This is a sample application which showcases the new PayPal REST APIs. The app uses mock data to demonstrate how you can use the REST APIs for
    %ul
      %li Saving credit card information with PayPal for later use.
      %li Making payments using a saved credit card.
      %li Making payments using PayPal.

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "PizzaShop"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
  %body
    .navbar.navbar-static-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar

          %ul.nav.pull-right
            - if user_signed_in?
              = active_li "Profile", edit_user_registration_path
              = active_li "SignOut", destroy_user_session_path
            - else
              = active_li "SignIn",  new_user_session_path
              = active_li "SignUp",  new_user_registration_path

          %a.brand{:href => "#"} PizzaShop
          .nav-collapse
            %ul.nav
              = active_li "Home", root_path
              - if user_signed_in?
                = active_li "Orders", orders_path
    #content.container
      = bootstrap_flash
      = yield
    #footer.navbar.navbar-fixed-bottom
      .navbar-inner
        .container
          %p.pull-right Powered by PayPal REST APIs
    = javascript_include_tag "application"

app/views/orders/create.html.haml
%h2 Place Order

= simple_form_for @order do |f|
  = f.error_notification
  .control-group
    = f.label :amount, :required => false
    .controls
      %label.checkbox
        = @order.amount
      = f.hidden_field :amount
  .control-group
    = f.label :description, :required => false
    .controls
      %label.checkbox
        = @order.description
        = f.error :description
      = f.hidden_field :description
  - if current_user.credit_card_id
    = f.input :payment_method, :as => :select, :collection => [ :credit_card, :paypal ], :include_blank => false, :hint => "Update your credit card in Profile page"
  - else
    = f.input :payment_method, :as => :select, :collection => [ :credit_card, :paypal ], :include_blank => false
    %legend New Credit Card
    = f.fields_for :credit_card, @order.credit_card do |cc|
      = render "users/registrations/credit_card", :f => cc

  .form-actions
    = f.button :submit, "Place Order", :class => "btn btn-primary"

app/views/orders/index.html.haml
%h2 Orders

%table.table
  %thead
    %tr
      %th Payment ID
      %th Amount($)
      %th Payment Status
      %th Time
      %th Description
      %th
  %tbody
    - @orders.each do |order|
      %tr
        %td= order.payment_id
        %td= order.amount
        %td= order.state
        %td= order.created_at
        %td= order.description
        %td= link_to "Details", order_path(order)

app/views/orders/show.html.haml
%h2 Order

%p
  %label Amount
  = @order.amount
%p
  %label Description
  = @order.description

%p
  %label Payment
  - if @order.payment.present?
    - if @order.payment.state == "approved"
      Payed with
      = @order.payment.payer.payment_method
    - elsif @order.approve_url
      = link_to "Pay with PayPal", @order.approve_url
    - else
      Payment or completed(#{@order.payment.state})

app/views/users/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>